# Generated by Django 5.2.1 on 2025-05-09 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('chips', 'Chips'), ('juice', 'Jus naturels'), ('yogurt', 'Yaourts'), ('croquettes', 'Croquettes'), ('caramel', 'Caramels'), ('crepes', 'Crêpes'), ('pizza', 'Pizza'), ('nems', 'Nems'), ('pile', 'Pilé (plat traditionnel)'), ('cake', 'Gâteaux'), ('other', 'Autre')], default='other', max_length=50, verbose_name='category type'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backed.category', verbose_name='category'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='image')),
                ('is_main', models.BooleanField(default=False, verbose_name='is main image')),
                ('alt_text', models.CharField(blank=True, max_length=100, verbose_name='alternative text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='backed.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product image',
                'verbose_name_plural': 'product images',
                'ordering': ['-is_main', '-created_at'],
            },
        ),
    ]
