# Generated by Django 5.2.1 on 2025-05-10 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0002_remove_category_created_at_and_more'),
    ]

    operations = [
    ]
