# Generated by Django 5.2.1 on 2025-05-10 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0003_auto_20250510_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='BueaDelights', max_length=100, verbose_name='site name')),
                ('contact_email', models.EmailField(default='admin@bueadelights.com', max_length=254, verbose_name='contact email')),
                ('contact_phone', models.CharField(default='237695922065', max_length=15, verbose_name='contact phone')),
                ('whatsapp_number', models.CharField(default='237695922065', max_length=15, verbose_name='WhatsApp number')),
                ('delivery_fee', models.PositiveIntegerField(default=1000, verbose_name='standard delivery fee')),
                ('noupia_merchant_id', models.CharField(blank=True, max_length=100, verbose_name='Noupia merchant ID')),
                ('noupia_api_key', models.CharField(blank=True, max_length=100, verbose_name='Noupia API key')),
                ('noupia_api_secret', models.CharField(blank=True, max_length=100, verbose_name='Noupia API secret')),
                ('notification_emails', models.TextField(default='admin@bueadelights.com', help_text='Comma-separated list of email addresses to receive order notifications', verbose_name='notification emails')),
                ('email_sender', models.EmailField(default='noreply@bueadelights.com', max_length=254, verbose_name='email sender address')),
                ('email_password', models.CharField(blank=True, max_length=100, verbose_name='email password')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='updated at'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='delivery address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('total_amount', models.PositiveIntegerField(verbose_name='total amount')),
                ('delivery_fee', models.PositiveIntegerField(default=1000, verbose_name='delivery fee')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='product name')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backed.order', verbose_name='order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='backed.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'order item',
                'verbose_name_plural': 'order items',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='transaction ID')),
                ('payment_method', models.CharField(choices=[('noupia', 'Noupia'), ('momo', 'MTN Mobile Money'), ('om', 'Orange Money'), ('cash', 'Cash')], max_length=20, verbose_name='payment method')),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('provider_reference', models.CharField(blank=True, max_length=100, verbose_name='provider reference')),
                ('payment_details', models.JSONField(blank=True, default=dict, verbose_name='payment details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='backed.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
