# Generated by Django 5.2.1 on 2025-05-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0004_sitesettings_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='folefacvivianekokobe@gmail.com', max_length=254, verbose_name='contact email'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='237699808260', max_length=15, verbose_name='contact phone'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='237699808260', max_length=15, verbose_name='WhatsApp number'),
        ),
    ]
