# Generated by Django 5.2.1 on 2025-05-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backed', '0005_alter_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_sender',
            field=models.EmailField(default='folefacvivianekokobe@gmail.com', max_length=254, verbose_name='email sender address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='notification_emails',
            field=models.TextField(default='folefacvivianekokobe@gmail.com', help_text='Comma-separated list of email addresses to receive order notifications', verbose_name='notification emails'),
        ),
    ]
